apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon-openvino-simple-server
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  name: "{{ .Release.Name }}"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: "{{ .Values.tfserving_proxy.image }}"
          name: tfserving-proxy
          resources:
            limits:
              cpu: "{{ .Values.openvino.limits.cpu }}"
              memory: "{{ .Values.openvino.limits.memory }}"
            requests:
              cpu: "{{ .Values.openvino.requests.cpu }}"
              memory: "{{ .Values.openvino.requests.memory }}"
        - name: openvino-model-server
          image: "{{ .Values.openvino.image }}"
          command:
          - "/ie-serving-py/start_server.sh"
          args:
          - ie_serving
          - model
          - "--model_path"
          - "{{ .Values.openvino.model.path }}"
          - "--model_name"
          - "{{ .Values.openvino.model.name }}"
          - "--port"
          - "{{ .Values.openvino.port }}"
          ports:
          - name: grpc
            containerPort: {{ .Values.openvino.port }}
            protocol: TCP
          env:
          - name: LOG_LEVEL
            value: DEBUG
          resources:
            limits:
              cpu: "{{ .Values.openvino.limits.cpu }}"
              memory: "{{ .Values.openvino.limits.memory }}"
            requests:
              cpu: "{{ .Values.openvino.requests.cpu }}"
              memory: "{{ .Values.openvino.requests.memory }}"
        terminationGracePeriodSeconds: 1
      hpaSpec:
        minReplicas: 1
        maxReplicas: 3
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 50
    graph:
      name: tfserving-proxy
      endpoint:
        type: GRPC
      type: MODEL
      children: []
      parameters:
      - name: grpc_endpoint
        type: STRING
        value: localhost:{{ .Values.openvino.port }}
      - name: model_name
        type: STRING
        value: "{{ .Values.openvino.model.name }}"
      - name: model_output
        type: STRING
        value: "{{ .Values.openvino.model.output }}"
      - name: model_input
        type: STRING
        value: "{{ .Values.openvino.model.input }}"
    name: openvino
    replicas: 1
